### Adicionar colaborador
POST http://localhost:3000/colaborador/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjYmNmM2QxNC03NWVmLTRjNDQtYjgwYy1jYmFhM2RjYzZmYTMiLCJlbWFpbCI6ImpvYW8ucmFiZWxsb0BleGFtcGxlLmNvbSIsInJvbGVzIjpbIkFETUlOIl0sImlhdCI6MTc1MDc5ODQyNywiZXhwIjoxNzUwODg0ODI3fQ.nwNhdi_egLiU64lo4QaPgIUW7PyqRNolXPfz5OqskVc

{
    "nomeCompleto": "Sardinha ",
    "email": "sardinha@example.com",
    "senha": "senha123",
    "cargo": "FINANCEIRO",
    "trilhaCarreira": "FINANCEIRO",
    "unidade": "RECIFE"
}

### Remover colaborador
DELETE http://localhost:3000/colaborador/remover/9aa7e53a-0518-4c53-b03b-2cee1b8cbc87
### Get colaborador

GET http://localhost:3000/colaborador/get/9aa7e53a-0518-4c53-b03b-2cee1b8cbc87

### Atualizar colaborador
PUT http://localhost:3000/colaborador/atualizar/c3ff70b4-1096-41aa-bba4-0cec649580da
Content-Type: application/json

{
    
    "email": "marcos.vinicius@example.com"
    
}

### Associar perfil
POST http://localhost:3000/colaborador/associar-perfil
Content-Type: application/json

{
    "tipoPerfil": "COLABORADOR_COMUM",
    "idColaborador": "379763a7-db56-4b79-a9f1-f3212a33a7e2"
}

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "joao.rabello@example.com",
    "senha": "senha123"
}


### Criar ciclo
POST http://localhost:3000/ciclo
Content-Type: application/json

{
    "nome": "2025.2",
    "dataInicioAno": 2025,
    "dataInicioMes": 6,
    "dataInicioDia": 25,
    "dataFimAno": 2025,
    "dataFimMes": 7,
    "dataFimDia":19
}

### Remover ciclo
DELETE http://localhost:3000/ciclo/remover/d7087ccd-575e-4586-aeb7-c8454d4f2ea3

### Get ciclo
GET http://localhost:3000/ciclo/get/b55004c9-4656-42ab-8b61-ebcd701fd2d6

### Get all ciclos
GET http://localhost:3000/ciclo/get-all

### Get ciclos ativos
GET http://localhost:3000/ciclo/get-ativos

### Get historico ciclos
GET http://localhost:3000/ciclo/get-historico

### Atualizar ciclo
PUT http://localhost:3000/ciclo/5fb2b328-edd7-4734-ac2a-cae9c3d18bf1
Content-Type: application/json

{
    "nome": "2025.28"
}

### Criar criterio
POST http://localhost:3000/criterios
Content-Type: application/json

{
  "nomeCriterio": "Comunicação",
  "descricao": "Avalia se o colaborador cumpre prazos e horários.",
  "peso": 1.0,
  "obrigatorio": true,
  "pilar": "Comportamento"
}

### Associar criterio ao ciclo
POST http://localhost:3000/associacoes-criterio-ciclo
Content-Type: application/json

{
    "idCiclo": "27e66525-41e2-46d5-9d16-be5e2d37daf4",
    "idCriterio": "6e74f93e-c81e-4ac7-9c81-cf08f052e55a",
    "trilhaCarreira": "SUPORTE",
    "cargo": "SUPORTE",
    "unidade": "SAO PAULO"
}

### Associar ciclo ao colaborador
POST http://localhost:3000/colaborador/associar-ciclo
Content-Type: application/json

{
    "idCiclo": "27e66525-41e2-46d5-9d16-be5e2d37daf4",
    "idColaborador": "0526ff8f-fd94-4548-a61e-b96fed2976d3"
}

### Lançar avaliações de pares
POST http://localhost:3000/avaliacoes/lancar-pares
Content-Type: application/json

{
    "idCiclo": "4e4b287f-bddd-47c7-83ff-a663720f2ba3"
}

### Lançar auto-avaliações
POST http://localhost:3000/avaliacoes/lancar-auto-avaliacoes
Content-Type: application/json

{
    "idCiclo": "4e4b287f-bddd-47c7-83ff-a663720f2ba3"
}


### Lançar avaliações de lideres
POST http://localhost:3000/avaliacoes/lancar-lider-colaborador
Content-Type: application/json

{
    "idCiclo": "4e4b287f-bddd-47c7-83ff-a663720f2ba3"
}

### Lançar avaliações mentor-colaborador
POST http://localhost:3000/avaliacoes/lancar-colaborador-mentor
Content-Type: application/json

{
    "idCiclo": "27e66525-41e2-46d5-9d16-be5e2d37daf4"
}


### GET Avaliações por usuário e tipo
GET http://localhost:3000/avaliacoes/tipo/usuario/0526ff8f-fd94-4548-a61e-b96fed2976d3?tipoAvaliacao=AVALIACAO_PARES

### GET Avaliações por usuário e tipo
GET http://localhost:3000/avaliacoes/status/4e4b287f-bddd-47c7-83ff-a663720f2ba3?status=PENDENTE

### Preencher avaliação pares
POST http://localhost:3000/avaliacoes/preencher-avaliacao-pares
Content-Type: application/json

{
    "idAvaliacao": "c4d51c0d-d849-4495-b3bb-e12d6ffd8aab",
    "nota": 5,
    "motivacao": "Concordo Totalmente",
    "pontosFortes": "Pontos Fortes",
    "pontosFracos": "Pontos Fracos"
}

### Preencher avaliação colaborador mentor
POST http://localhost:3000/avaliacoes/preencher-avaliacao-colaborador-mentor
Content-Type: application/json

{
    "idAvaliacao": "c4d51c0d-d849-4495-b3bb-e12d6ffd8aab",
    "nota": 3.7,
    "justificativa": "Justificativa"
}