### Adicionar colaborador
POST http://localhost:3000/colaborador/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjYmNmM2QxNC03NWVmLTRjNDQtYjgwYy1jYmFhM2RjYzZmYTMiLCJlbWFpbCI6ImpvYW8ucmFiZWxsb0BleGFtcGxlLmNvbSIsInJvbGVzIjpbIkFETUlOIl0sImlhdCI6MTc1MDc5ODQyNywiZXhwIjoxNzUwODg0ODI3fQ.nwNhdi_egLiU64lo4QaPgIUW7PyqRNolXPfz5OqskVc

{
    "nomeCompleto": "GESTOR ",
    "email": "gestor@example.com",
    "senha": "senha123",
    "colaboradorComum": true,
    "gestor": true

}

### Remover colaborador
DELETE http://localhost:3000/colaborador/565a6f76-751e-4d01-bba3-a84f313c80bf
### Get colaborador

GET http://localhost:3000/colaborador/get/9aa7e53a-0518-4c53-b03b-2cee1b8cbc87

### Get all colaboradores
GET http://localhost:3000/colaborador/get-all-colaboradores



### Atualizar colaborador
PUT http://localhost:3000/colaborador/atualizar/c3ff70b4-1096-41aa-bba4-0cec649580da
Content-Type: application/json

{
    
    "email": "marcos.vinicius@example.com"
    
}

### Associar perfil
POST http://localhost:3000/colaborador/associar-perfil
Content-Type: application/json

{
    "tipoPerfil": "COLABORADOR_COMUM",
    "idColaborador": "33333333-3333-3333-3333-333333333333"
}

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "admin@example.com",
    "senha": "senha123"
}


### Criar ciclo
POST http://localhost:3000/ciclo
Content-Type: application/json

{
    "nome": "2025.8",
    "dataInicioAno": 2025,
    "dataInicioMes": 6,
    "dataInicioDia": 10,
    "dataFimAno": 2025,
    "dataFimMes": 7,
    "dataFimDia": 3,
    "duracaoEmAndamentoDias": 22,
    "duracaoEmRevisaoDias": 1,
    "duracaoEmEqualizacaoDias": 2
}

### Remover ciclo
DELETE http://localhost:3000/ciclo/d18b8e43-5535-425e-bc73-88f393286fbc
### Get ciclo
GET http://localhost:3000/ciclo/get/b55004c9-4656-42ab-8b61-ebcd701fd2d6

### Get all ciclos
GET http://localhost:3000/ciclo/get-all

### Get ciclos ativos
GET http://localhost:3000/ciclo/get-ativos

### Get historico ciclos
GET http://localhost:3000/ciclo/get-historico

### Atualizar ciclo
PUT http://localhost:3000/ciclo/5fb2b328-edd7-4734-ac2a-cae9c3d18bf1
Content-Type: application/json

{
    "nome": "2025.28"
}

### Criar criterio
POST http://localhost:3000/criterios
Content-Type: application/json

{
  "nomeCriterio": "Teste",
  "descricao": "Testando pesos",
  "peso": 3.0,
  "obrigatorio": true,
  "pilar": "Comportamento"
}

### Associar criterio ao ciclo
POST http://localhost:3000/associacoes-criterio-ciclo
Content-Type: application/json

{
    "idCiclo": "55555555-5555-5555-5555-666666666666",
    "idCriterio": "871ff8c0-f001-4faf-8e64-4ec40764d80c"
}

### Associar ciclo ao colaborador
POST http://localhost:3000/colaborador/associar-ciclo
Content-Type: application/json

{
    "idCiclo": "55555555-5555-5555-5555-666666666666",
    "idColaborador": "44444444-4444-4444-4444-444444444444"
}

### Lançar avaliações de pares
POST http://localhost:3000/avaliacoes/lancar-pares
Content-Type: application/json

{
    "idCiclo": "4e4b287f-bddd-47c7-83ff-a663720f2ba3"
}

### Lançar auto-avaliações
POST http://localhost:3000/avaliacoes/lancar-auto-avaliacoes
Content-Type: application/json

{
    "idCiclo": "55555555-5555-5555-5555-666666666666"
}

### Lançar todas as avaliações
POST http://localhost:3000/avaliacoes
Content-Type: application/json

{
    "idCiclo": "55555555-5555-5555-5555-666666666666"
}

### Lançar avaliações de lideres
POST http://localhost:3000/avaliacoes/lancar-lider-colaborador
Content-Type: application/json

{
    "idCiclo": "55555555-5555-5555-5555-666666666666"
}

### Lançar avaliações mentor-colaborador
POST http://localhost:3000/avaliacoes/lancar-colaborador-mentor
Content-Type: application/json

{
    "idCiclo": "55555555-5555-5555-5555-666666666666"
}


### GET Avaliações por usuário e tipo
GET http://localhost:3000/avaliacoes/tipo/usuario/0526ff8f-fd94-4548-a61e-b96fed2976d3?tipoAvaliacao=AVALIACAO_PARES

### GET Avaliações por usuário e tipo
GET http://localhost:3000/avaliacoes/status/4e4b287f-bddd-47c7-83ff-a663720f2ba3?status=PENDENTE

### Preencher avaliação pares
POST http://localhost:3000/avaliacoes/preencher-avaliacao-pares
Content-Type: application/json

{
    "idAvaliacao": "fb45d877-257c-4b93-a544-522a0647f650",
    "nota": 5,
    "motivacao": "Concordo Totalmente",
    "pontosFortes": "Pontos Fortes",
    "pontosFracos": "Pontos Fracos"
}

### Preencher avaliação colaborador mentor
POST http://localhost:3000/avaliacoes/preencher-avaliacao-colaborador-mentor
Content-Type: application/json

{
    "idAvaliacao": "317215a6-8a7c-457c-98cb-47da3792b821",
    "nota": 3.5,
    "justificativa": "Justificativa"
}

### Preencher autoavaliação
POST http://localhost:3000/avaliacoes/preencher-auto-avaliacao
Content-Type: application/json

{
    "idAvaliacao": "4780304d-1d37-48c9-9721-10ccdbe54780",
    "criterios": [
        {
            "nome": "Comunicação",
            "nota": 5.0,
            "justificativa": "Acredito que me comuniquei da melhor forma possivel"
        },
        {
            "nome": "Trabalho em Equipe",
            "nota": 5.0,
            "justificativa": "Colaborei bem com o time em todos os projetos"
        },
        {
            "nome": "Adaptabilidade",
            "nota": 5.0,
            "justificativa": "Me adaptei rapidamente às mudanças de escopo"
        },
        {
            "nome": "Qualidade das Entregas",
            "nota": 1.5,
            "justificativa": "Entreguei todas as tarefas com alta qualidade"
        },
        {
            "nome": "Cumprimento de Prazos",
            "nota": 3.0,
            "justificativa": "Cumpri todos os prazos estabelecidos"
        },
        {
            "nome": "Resolução de Problemas",
            "nota": 2.0,
            "justificativa": "Resolvi problemas complexos de forma eficiente"
        },
        {
            "nome": "Gestão de Projetos",
            "nota": 1.0,
            "justificativa": "Gerenciei projetos de forma organizada"
        },
        {
            "nome": "Tomada de Decisão",
            "nota": 4.0,
            "justificativa": "Tomei decisões assertivas em situações críticas"
        },
        {
            "nome": "Desenvolvimento de Equipe",
            "nota": 1.0,
            "justificativa": "Tomei decisões assertivas em situações críticas"
        },
        {
            "nome": "Teste",
            "nota": 5.0,
            "justificativa": "Tomei decisões assertivas em situações críticas"
        }
        

    ]
}

### Preencher lide-colaborador

POST http://localhost:3000/avaliacoes/preencher-lider-colaborador
Content-Type: application/json

{
    "idAvaliacao": "2ffefec2-5f13-411b-9bf1-cb4d7e4603d2",
    "criterios": [
        {
            "nome": "Comunicação",
            "nota": 5.0,
            "justificativa": "Acredito que me comuniquei da melhor forma possivel"
        },
        {
            "nome": "Trabalho em Equipe",
            "nota": 5.0,
            "justificativa": "Colaborei bem com o time em todos os projetos"
        },
        {
            "nome": "Adaptabilidade",
            "nota": 4.0,
            "justificativa": "Me adaptei rapidamente às mudanças de escopo"
        },
        {
            "nome": "Qualidade das Entregas",
            "nota": 5.0,
            "justificativa": "Entreguei todas as tarefas com alta qualidade"
        },
        {
            "nome": "Cumprimento de Prazos",
            "nota": 5.0,
            "justificativa": "Cumpri todos os prazos estabelecidos"
        },
        {
            "nome": "Resolução de Problemas",
            "nota": 5.0,
            "justificativa": "Resolvi problemas complexos de forma eficiente"
        },
        {
            "nome": "Gestão de Projetos",
            "nota": 5.0,
            "justificativa": "Gerenciei projetos de forma organizada"
        },
        {
            "nome": "Tomada de Decisão",
            "nota": 5.0,
            "justificativa": "Tomei decisões assertivas em situações críticas"
        },
         {
            "nome": "Desenvolvimento de Equipe",
            "nota": 4.5,
            "justificativa": "Tomei decisões assertivas em situações críticas"
        }

    ]
}

### Relacionar Líder-Colaborador
POST http://localhost:3000/colaborador/relacionar-lider-colaborador
Content-Type: application/json

{
  "idLider": "33333333-3333-3333-3333-333333333333",
  "idColaborador": "44444444-4444-4444-4444-444444444444",
  "idCiclo": "55555555-5555-5555-5555-666666666666"
}

### Relacionar Mentor-Colaborador
POST http://localhost:3000/colaborador/relacionar-mentor-colaborador
Content-Type: application/json

{
  "idMentor": "22222222-2222-2222-2222-222222222222",
  "idColaborador": "11111111-1111-1111-1111-111111111111",
  "idCiclo": "55555555-5555-5555-5555-666666666666"
}

### Get constantes
GET http://localhost:3000/colaborador/constantes
